project_id = "rgypfqxiqeymltbinkvs"

[functions.calculate-all-bonificaciones]
verify_jwt = false

[functions.calculate-bonificaciones]
verify_jwt = false

[functions.process-creator-analytics]
verify_jwt = true

[functions.generate-creator-advice]
verify_jwt = true

[functions.manage-user]
verify_jwt = true