project_id = "rgypfqxiqeymltbinkvs"

# ==============================================
# CONFIGURACIÓN DE PRODUCCIÓN
# ==============================================
# Todas las edge functions requieren autenticación JWT
# para proteger datos sensibles de bonificaciones

[functions.calculate-bonificaciones]
verify_jwt = true

[functions.calculate-all-bonificaciones]
verify_jwt = true

[functions.process-creator-analytics]
verify_jwt = true

[functions.generate-creator-advice]
verify_jwt = true

[functions.manage-user]
verify_jwt = true

# Función de generación de datos demo (solo desarrollo)
# IMPORTANTE: Desactivar o eliminar en producción final
[functions.generate-demo-live-data]
verify_jwt = true
