// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgypfqxiqeymltbinkvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJneXBmcXhpcWV5bWx0Ymlua3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5NTA3NTUsImV4cCI6MjA3NTUyNjc1NX0.mTbYnjc3JTIyEQNSQbWIGqrh4BU1DRZkOr06EyWevYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});